WATCHLIST = ["BTC", "ETH", "SOL"]
INTERVAL_MINUTES = 5
MAX_TRADES_PER_DAY = 50
MIN_CONFIDENCE = 55
MAX_LOSS_PERCENT = 5
TAKE_PROFIT_PERCENT = 2.5
STOP_LOSS_PERCENT = 1.5
CIRCUIT_BREAKER_THRESHOLD = -5.0
PAPER_MODE = True

# Paper trading portfolio
PAPER_BALANCE = 10000.0
MAX_POSITION_PCT = 40
RISK_PER_TRADE = 5

# Blockchain settings
SEPOLIA_RPC = "https://ethereum-sepolia-rpc.publicnode.com"
GAS_MULTIPLIER = 2.0
TX_TIMEOUT = 300
