WATCHLIST = ["BTC", "ETH", "SOL"]
INTERVAL_MINUTES = 5
MAX_TRADES_PER_DAY = 50
MIN_CONFIDENCE = 55
MAX_LOSS_PERCENT = 5
TAKE_PROFIT_PERCENT = 1.2
STOP_LOSS_PERCENT = 0.8
CIRCUIT_BREAKER_THRESHOLD = -5.0
PAPER_MODE = True

# Blockchain settings
GAS_MULTIPLIER = 2.0  # reduced from 3.0 for less aggressive pricing
TX_TIMEOUT = 300
